name: design_token
description: "A new Flutter project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  diacritic: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom-icons.ttf

    - family: FaBrands400
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf